/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Scanner;


public class ReminderShow extends javax.swing.JFrame {

    ArrayList<Notes>n=new ArrayList<Notes>();
    public ReminderShow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        r = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        r.setText("select enter");
        r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(r, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void rActionPerformed(java.awt.event.ActionEvent evt) {                                  
        // TODO add your handling code here:
        search();
    }                                 
   public void print(String sub,String tex,String dat,String hou) {
    	 r.setText(r.getText()+"****"+sub+" "+tex+" "+dat+" "+hou);
    	 
     }
    public  void load() {
         
			
			try{
			 FileReader reader=new FileReader("D:\\uni\\eng\\java\\eclipse\\CalenderTest\\file.txt");
			 Scanner in=new Scanner(reader);
			 while(in.hasNextLine()){
				 String line=in.nextLine();
				 String part[]=line.split(" ");
				 Notes note=new Notes(part[0],part[1],part[2],part[3]);
		         n.add(note);
		         
			 }
			 in.close();
		 }
		 catch(FileNotFoundException ex){
			 System.out.println("file not found");
		 }
			
		}
    public  void search() {
    int count=0;
	CalendarProgram c=new CalendarProgram();
	 
        load();
	for(Notes note:n) {
		String part[]=note.date.split("/");
                
		if(Integer.parseInt(part[1])==c.currentMonth && Integer.parseInt(part[0])==c.currentYear &&Integer.parseInt(part[2])==c.realDay) {
                
			print(note.subject,note.text,note.date,note.hou);
                        count++;
                
		
                }
	}
        if(count==0){
            r.setText("There is not any works");
        }
	
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReminderShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReminderShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReminderShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReminderShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReminderShow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField r;
    // End of variables declaration                   
}
